### ISSUE TITLE
'get_property' failed

### ISSUE THREAD

**Issue by shevchuk** [mihaiolteanu/vuiet#31]
Sometimes when start playing album using `vuiet-play-album` I get:
```
error in process filter: mpv-run-command: ‘get_property’ failed: property unavailable
error in process filter: ‘get_property’ failed: property unavailable
```

After several retries it starts to play.

**Comment by mihaiolteanu** [comment]
Only for an album play?
I also get that error sometimes when trying to change the playlists.
I believe mpv gets in a state when no track is loaded even though it erroneously returns that a track is actually loaded. It then tries to get that track property, and it fails. But I haven't manage to figure out the exact time and place where this error happens.

Thanks for you input!
Everything working out ok otherwise?

**Comment by mihaiolteanu** [comment]
Solution: update the youtube-dl to the latest version,
http://ytdl-org.github.io/youtube-dl/download.html
